- name: Set wlan0 to promiscuous mode for MetalLB
  copy:
    dest: /etc/networkd-dispatcher/routable.d/00-wlan0-promisc.sh
    src: etc/networkd-dispatcher/routable.d/00-wlan0-promisc.sh
    owner: root
    group: root
    mode: '0750'
  notify: set wlan0 to promiscuous mode

- name: install packages to support Docker repo
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: latest

- name: import Docker GPG key
  apt_key:
    keyserver: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: add Docker repo
  apt_repository:
    repo: deb [arch=arm64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: add Kubernetes GPG key
  apt_key:
    keyserver: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    id: 54A647F9048D5688D7DA2ABE6A030B21BA07F4FB
    state: present

- name: add Kubernetes repo
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: install Docker and Kubernetes packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: hold Kubernetes package versions
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubelet
    - kubeadm
    - kubectl
  tags: debug
