- name: grab token and command for joining hosts
  shell:
    cmd: kubeadm token create --print-join-command 2>/dev/null
  register: kubeadm_token_command
  delegate_to: "{{ groups['k8s_control_plane'][0] }}"
  run_once: True

- name: join node to cluster
  command:
    cmd: "{{ kubeadm_token_command.stdout }}"
