- name: netplan apply
  command:
    cmd: /usr/sbin/netplan apply

# Credit: https://earlruby.org/2019/07/rebooting-a-host-with-ansible/
- name: restart and wait
  reboot:
    msg: "Rebooting to update GRUB config"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
